spring.application.name=backend

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


spring.data.mongodb.uri=mongodb://localhost:27017/passwordtracker